// Original effects only; no background music is generated or packaged.
const sfx = (id,title,seconds,prompt) => ({id,title,type:'sfx',seconds,prompt:`${prompt}; isolated dry game sound, immediate onset and clean short decay, no voice, music or background ambience.`});
const gear = [
 ['artillery','견인포',1.2,'A single field artillery cannon firing, sharp report with a rounded bass thump and a brief breech rattle',1,'A field gun breech locking with one solid metal clunk'],
 ['tank','전차',1.2,'A single tank cannon shot, tight heavy low punch with a sharp metallic crack',1.3,'A short armored tracked vehicle engine rev and track clatter'],
 ['selfPropelled','자주포',1.5,'A single heavy self-propelled howitzer shot, deep booming punch with brief barrel resonance',1.2,'A heavy hydraulic cannon carriage locking into firing position'],
 ['helicopter','공격헬기',0.8,'A short three-shot helicopter autocannon burst, tight staccato mechanical reports',1.5,'A short close helicopter rotor spin-up with a rising turbine whine'],
 ['rocketLauncher','다연장 로켓포',1.5,'A short three-rocket launch burst with rapidly staggered fiery whooshes',1.2,'A rocket pod elevation motor finishing with a locking latch'],
 ['transport','전술 수송기',1.4,'A gentle electronic medical repair pulse, soft ascending synthetic tones with a warm shimmering tail',1.5,'A short heavy transport aircraft propeller and turbine flyby'],
 ['fighter','전투기',1.2,'A short jet missile ignition and sharp supersonic rushing whoosh',1.5,'A fast fighter jet turbine flyby, concise rising and falling pitch'],
 ['railgunTank','레일건 전차',1.4,'A single electromagnetic cannon discharge, bright electric crack and deep compressed impact with a brief ionized tail',1.2,'A heavy electric power core charging and locking with a metallic click'],
 ['icbm','ICBM',2,'A large strategic rocket igniting, deep ignition thump followed by a powerful short rocket roar',1.4,'A heavy missile launch tube hydraulic hatch opening and locking'],
];
export const SFX_PLAN = [...gear.flatMap(([id,name,sec,action,deploySec,deploy])=>[sfx(`${id}-action`,`${name} 공격·지원`,sec,action),sfx(`${id}-deploy`,`${name} 출격`,deploySec,deploy)]),
 sfx('turret-shot','본부 포탑',0.6,'One crisp defensive autocannon shot with a compact metallic snap'),
 sfx('impact','탄착',0.6,'One bullet striking armor, sharp dry metallic ping and blunt impact'),
 sfx('explosion','장비 파괴',1.4,'A compact armored vehicle explosion, low burst with a short metallic debris rattle'),
 sfx('base-hit','본부 피격',1.1,'A heavy shell striking reinforced concrete, low thud with short crumbling debris'),
 sfx('battle-start','작전 개시',1.5,'A concise military electronic alert with three determined descending-to-rising pulses'),
 sfx('victory','승리',3,'A short original triumphant orchestral fanfare with bright brass and a crisp snare finish'),
 sfx('defeat','패배',2.5,'A short restrained descending low brass and soft timpani stinger, solemn and calm'),
 sfx('draw','무승부',1.8,'A short neutral suspended two-tone low brass stinger without triumph or tragedy'),
 sfx('tap','골드 터치',0.5,'A single light dry coin tick, soft rounded metallic click without ringing'),
 sfx('click','메뉴 선택',0.5,'A single soft tactile military radio switch click'),
 sfx('recruit','병력 모집',1,'A compact original ascending two-note confirmation with a soft boot-step thump'),
 sfx('purchase','장비 구매',1.1,'A short satisfied mechanical acquisition chime with a neat metallic clasp'),
 sfx('build','학교 건설',1.5,'A short solid construction completion sound, ratchet locking into a resonant metal thump'),
 sfx('equip','장비 배치',0.6,'A single firm equipment mounting latch snapping into place'),
 sfx('upgrade-success','강화 성공',1.6,'A bright original ascending metallic shimmer ending in a clear satisfying chime'),
 sfx('upgrade-fail','강화 실패',1,'A gentle low double electronic rejection pulse with a soft mechanical release, not harsh'),
 sfx('promotion','진급',3,'A short original dignified military promotion fanfare, rising brass notes and a restrained snare flourish'),
 sfx('medal','훈장 획득',1.6,'A clear original honor-award chime, polished bell tones with a warm sustained resonance'),
 sfx('sword','장군검 발동',1.1,'A ceremonial sword drawn from a scabbard, clean bright metallic ring with a brief airy sweep'),
 sfx('revolver','리볼버 발동',0.8,'A revolver cylinder indexing and hammer cocking with one crisp mechanical snap'),
 sfx('error','조작 불가',0.5,'A soft low two-tap interface rejection sound without alarming buzzer'),
 sfx('unlock','해금',1.2,'A secure mechanical lock opening with a subtle bright ascending confirmation chime'),
];
export const AUDIO_PLAN = SFX_PLAN;
