// Original production briefs: no artists, existing scores, real anthems, voices or recordings.
const music = (id, title, prompt) => ({id, title, type:'music', seconds:60, prompt:`Original instrumental hybrid orchestral strategy game underscore. ${prompt} Subtle pixel-synth texture, clean production, even dynamics, repeating harmony suitable for continuous looping; no vocals, long intro or final cadence, leave space for short gameplay sounds.`});
export const MUSIC_PLAN = [
  music('home','주둔지의 아침','Calm and resolute at 88 BPM, warm French horns, muted snare march, restrained strings and soft analog pulse.'),
  music('map','작전 지도','Focused tactical suspense at 92 BPM, low cello ostinato, muted sonar-like synth plucks, brushed snare and sparse warm horns.'),
  music('serdin-early','세르딘 · 해안 진군','Measured hopeful march at 104 BPM, light snare, open horn intervals, airy woodwinds, plucked strings and soft bass drum.'),
  music('serdin-middle','세르딘 · 들판 교전','Determined march at 112 BPM, interlocking string ostinato, snare rolls, rounded brass answers and gently rising minor harmony.'),
  music('serdin-late','세르딘 · 성벽 접근','Urgent grounded orchestral tension at 122 BPM, low string pulses, tight snare patterns, muted brass stabs and restrained timpani.'),
  music('serdin-capital','세르딘 · 수도 공성','High tension orchestral siege music at 132 BPM, urgent string ostinato, powerful low brass, syncopated timpani and metallic accents; minor harmonies sustain pressure without a triumphant resolution.'),
  music('veloc-early','벨로크 · 붉은 변경','Industrial orchestral pulse at 108 BPM, dry metallic percussion, low analog bass sequence, muted horns and short gritty cello phrases.'),
  music('veloc-middle','벨로크 · 철의 전선','Driving industrial rhythm at 120 BPM, mechanical tom patterns, metallic anvil accents, low brass chords and filtered synth ostinato.'),
  music('veloc-late','벨로크 · 병기창 돌파','Intense industrial orchestral rhythm at 132 BPM, angular strings, hammering metallic percussion, distorted low bass pulse and controlled brass stabs.'),
  music('veloc-capital','벨로크 · 강철 수도','Relentless high tension industrial siege score at 140 BPM, pounding low toms, metallic strikes, tense chromatic brass and urgent synth bass, sustained danger and no victory resolution.'),
  music('istra-early','이스트라 · 은호수','Mysterious measured orchestral movement at 100 BPM, delicate celesta, low strings, breathy woodwinds and soft frame drums, cool spacious minor harmonies.'),
  music('istra-middle','이스트라 · 고원 전투','Focused rising tension at 112 BPM, layered plucked strings, restrained flute accents, deep frame drums and cello ostinato with shimmering sparse bells.'),
  music('istra-late','이스트라 · 왕실 방어선','Urgent orchestral pursuit at 124 BPM, tremolo strings, angular cello ostinato, deep toms, dark horns and sparse high bell tones.'),
  music('istra-capital','이스트라 · 왕관 공성','Majestic but threatening orchestral siege at 136 BPM, sweeping minor strings, powerful low horns, rolling timpani and icy celesta accents, sustained unresolved tension.'),
  music('norgard-early','노르가드 · 눈보라','Cold imposing orchestral pulse at 110 BPM, deep bass drones, thin high strings, distant metallic bells, sparse heavy toms and restrained synth pulse.'),
  music('norgard-middle','노르가드 · 빙하 전선','Heavy determined orchestral rhythm at 124 BPM, low brass ostinato, icy high string texture, deep drums and crisp metallic strikes.'),
  music('norgard-late','노르가드 · 황제의 방벽','Severe urgent hybrid orchestral rhythm at 136 BPM, dense low string patterns, thunderous restrained percussion, dark brass and high crystalline accents.'),
  music('norgard-capital','노르가드 · 최후의 수도','Maximum tension final siege instrumental at 148 BPM, massive low brass ostinato, fast precise string figures, heavy toms and timpani, sharp icy bells, rising harmonic pressure; imposing and dangerous with no vocals or triumphant resolution.'),
];
const sfx = (id,title,seconds,prompt) => ({id,title,type:'sfx',seconds,prompt:`${prompt}; isolated dry game sound, immediate onset and clean short decay, no voice, music or background ambience.`});
const gear = [
 ['artillery','견인포',1.2,'A single field artillery cannon firing, sharp report with a rounded bass thump and a brief breech rattle',1,'A field gun breech locking with one solid metal clunk'],
 ['tank','전차',1.2,'A single tank cannon shot, tight heavy low punch with a sharp metallic crack',1.3,'A short armored tracked vehicle engine rev and track clatter'],
 ['selfPropelled','자주포',1.5,'A single heavy self-propelled howitzer shot, deep booming punch with brief barrel resonance',1.2,'A heavy hydraulic cannon carriage locking into firing position'],
 ['helicopter','공격헬기',0.8,'A short three-shot helicopter autocannon burst, tight staccato mechanical reports',1.5,'A short close helicopter rotor spin-up with a rising turbine whine'],
 ['rocketLauncher','다연장 로켓포',1.5,'A short three-rocket launch burst with rapidly staggered fiery whooshes',1.2,'A rocket pod elevation motor finishing with a locking latch'],
 ['transport','전술 수송기',1.4,'A gentle electronic medical repair pulse, soft ascending synthetic tones with a warm shimmering tail',1.5,'A short heavy transport aircraft propeller and turbine flyby'],
 ['fighter','전투기',1.2,'A short jet missile ignition and sharp supersonic rushing whoosh',1.5,'A fast fighter jet turbine flyby, concise rising and falling pitch'],
 ['railgunTank','레일건 전차',1.4,'A single electromagnetic cannon discharge, bright electric crack and deep compressed impact with a brief ionized tail',1.2,'A heavy electric power core charging and locking with a metallic click'],
 ['icbm','ICBM',2,'A large strategic rocket igniting, deep ignition thump followed by a powerful short rocket roar',1.4,'A heavy missile launch tube hydraulic hatch opening and locking'],
];
export const SFX_PLAN = [...gear.flatMap(([id,name,sec,action,deploySec,deploy])=>[sfx(`${id}-action`,`${name} 공격·지원`,sec,action),sfx(`${id}-deploy`,`${name} 출격`,deploySec,deploy)]),
 sfx('turret-shot','본부 포탑',0.6,'One crisp defensive autocannon shot with a compact metallic snap'),
 sfx('impact','탄착',0.6,'One bullet striking armor, sharp dry metallic ping and blunt impact'),
 sfx('explosion','장비 파괴',1.4,'A compact armored vehicle explosion, low burst with a short metallic debris rattle'),
 sfx('base-hit','본부 피격',1.1,'A heavy shell striking reinforced concrete, low thud with short crumbling debris'),
 sfx('battle-start','작전 개시',1.5,'A concise military electronic alert with three determined descending-to-rising pulses'),
 sfx('victory','승리',3,'A short original triumphant orchestral fanfare with bright brass and a crisp snare finish'),
 sfx('defeat','패배',2.5,'A short restrained descending low brass and soft timpani stinger, solemn and calm'),
 sfx('draw','무승부',1.8,'A short neutral suspended two-tone low brass stinger without triumph or tragedy'),
 sfx('tap','골드 터치',0.5,'A single light dry coin tick, soft rounded metallic click without ringing'),
 sfx('click','메뉴 선택',0.5,'A single soft tactile military radio switch click'),
 sfx('recruit','병력 모집',1,'A compact original ascending two-note confirmation with a soft boot-step thump'),
 sfx('purchase','장비 구매',1.1,'A short satisfied mechanical acquisition chime with a neat metallic clasp'),
 sfx('build','학교 건설',1.5,'A short solid construction completion sound, ratchet locking into a resonant metal thump'),
 sfx('equip','장비 배치',0.6,'A single firm equipment mounting latch snapping into place'),
 sfx('upgrade-success','강화 성공',1.6,'A bright original ascending metallic shimmer ending in a clear satisfying chime'),
 sfx('upgrade-fail','강화 실패',1,'A gentle low double electronic rejection pulse with a soft mechanical release, not harsh'),
 sfx('promotion','진급',3,'A short original dignified military promotion fanfare, rising brass notes and a restrained snare flourish'),
 sfx('medal','훈장 획득',1.6,'A clear original honor-award chime, polished bell tones with a warm sustained resonance'),
 sfx('sword','장군검 발동',1.1,'A ceremonial sword drawn from a scabbard, clean bright metallic ring with a brief airy sweep'),
 sfx('revolver','리볼버 발동',0.8,'A revolver cylinder indexing and hammer cocking with one crisp mechanical snap'),
 sfx('error','조작 불가',0.5,'A soft low two-tap interface rejection sound without alarming buzzer'),
 sfx('unlock','해금',1.2,'A secure mechanical lock opening with a subtle bright ascending confirmation chime'),
];
export const AUDIO_PLAN = [...MUSIC_PLAN,...SFX_PLAN];
